Repository mycroft16/test-release-notes, pull requests merged in 2019-09, with the labels that each got.

#1 Added product listing page
  products.html
Labels: added

#2 [BV-12] - Section tags should have been article tags
  index.html
Labels: updated

#3 [POL-437] - Create page for tracking product shipments
  track.html
Labels: added

#4 Makes a small change
  contact.html
Labels: added

#5 Change letter
  contact.html
Labels: changed

#6 [POL-446] - Removed tracking page
  track.html
Labels: removed

#7 [POL-449] - Changed letter
  contact.html
Labels: changed
